// Copyright 2026 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
// This file is generated by ts-to-schema, do not edit it directly.
// @ts-nocheck
/* cspell:disable */
import { type ICompiledValidator, JsonSchemaFormats } from "@3sixty/data-core";
import * as external0 from "@3sixty/standards-w3c-activity-streams";
import * as external1 from "@3sixty/data-json-ld";
const MESSAGES = [
	"must be string",
	"must match a schema in anyOf",
	"must be array",
	"must be object"
];
function createError(instancePath, schemaPath, keyword, params, message) {
	return {
		instancePath,
		schemaPath,
		keyword,
		params,
		["message"]: typeof message === "number" ? MESSAGES[message] : message
	};
}
function pushError(errors, error) {
	if (errors === null) {
		return [error];
	}
	errors.push(error);
	return errors;
}
/**
 * Compiled validator for the DataspaceActivity schema.
 */
export const CompiledDataspaceActivity: ICompiledValidator = validate52;
const keyword0 = external0["CompiledActivityStreamsContextType"];
const keyword1 = external0["CompiledActivityStreamsTypes"];
const keyword3 = external1["CompiledJsonLdLanguageMap"];
const keyword9 = external1["CompiledJsonLdNodeObject"];
const keyword50 = external1["CompiledJsonLdContextDefinitionRoot"];
const formats0 = JsonSchemaFormats.uri;
const formats2 = JsonSchemaFormats["date-time"];
const formats10 = /^P(?!$)((\d+Y)?(\d+M)?(\d+D)?(T(?=\d)(\d+H)?(\d+M)?(\d+S)?)?|(\d+W)?)$/;

function validate52(
	data,
	{ instancePath = "", parentData, parentDataProperty, rootData = data, dynamicAnchors = {} } = {}
) {
	/*# sourceURL="https://schema.3sixty.global/dataspace/DataspaceActivity" */ let vErrors = null;
	let errors = 0;
	const evaluated0 = validate52.evaluated;
	if (evaluated0.dynamicProps) {
		evaluated0.props = undefined;
	}
	if (evaluated0.dynamicItems) {
		evaluated0.items = undefined;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data["@context"] === undefined) {
			const err0 = createError(
				instancePath,
				"#/allOf/0/required",
				"required",
				{ missingProperty: "@context" },
				"must have required property '" + "@context" + "'"
			);
			vErrors = pushError(vErrors, err0);
			errors++;
		}
		if (data.type === undefined) {
			const err1 = createError(
				instancePath,
				"#/allOf/0/required",
				"required",
				{ missingProperty: "type" },
				"must have required property '" + "type" + "'"
			);
			vErrors = pushError(vErrors, err1);
			errors++;
		}
		if (data["@context"] !== undefined) {
			if (
				!keyword0(data["@context"], {
					instancePath: instancePath + "/@context",
					parentData: data,
					parentDataProperty: "@context",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword0.errors : vErrors.concat(keyword0.errors);
				errors = vErrors.length;
			}
		}
		if (data.type !== undefined) {
			let data1 = data.type;
			const _errs8 = errors;
			let valid2 = false;
			const _errs9 = errors;
			if (
				!keyword1(data1, {
					instancePath: instancePath + "/type",
					parentData: data,
					parentDataProperty: "type",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
				errors = vErrors.length;
			}
			var _valid0 = _errs9 === errors;
			valid2 = valid2 || _valid0;
			const _errs10 = errors;
			if (typeof data1 !== "string") {
				const err2 = createError(
					instancePath + "/type",
					"#/allOf/0/properties/type/anyOf/1/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err2);
				errors++;
			}
			var _valid0 = _errs10 === errors;
			valid2 = valid2 || _valid0;
			const _errs12 = errors;
			if (Array.isArray(data1)) {
				const len0 = data1.length;
				for (let i0 = 0; i0 < len0; i0++) {
					let data2 = data1[i0];
					const _errs15 = errors;
					let valid5 = false;
					const _errs16 = errors;
					if (
						!keyword1(data2, {
							instancePath: instancePath + "/type/" + i0,
							parentData: data1,
							parentDataProperty: i0,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword1.errors : vErrors.concat(keyword1.errors);
						errors = vErrors.length;
					}
					var _valid1 = _errs16 === errors;
					valid5 = valid5 || _valid1;
					const _errs17 = errors;
					if (typeof data2 !== "string") {
						const err3 = createError(
							instancePath + "/type/" + i0,
							"#/allOf/0/properties/type/anyOf/2/items/anyOf/1/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err3);
						errors++;
					}
					var _valid1 = _errs17 === errors;
					valid5 = valid5 || _valid1;
					if (!valid5) {
						const err4 = createError(
							instancePath + "/type/" + i0,
							"#/allOf/0/properties/type/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err4);
						errors++;
					} else {
						errors = _errs15;
						if (vErrors !== null) {
							if (_errs15) {
								vErrors.length = _errs15;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err5 = createError(
					instancePath + "/type",
					"#/allOf/0/properties/type/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err5);
				errors++;
			}
			var _valid0 = _errs12 === errors;
			valid2 = valid2 || _valid0;
			if (!valid2) {
				const err6 = createError(
					instancePath + "/type",
					"#/allOf/0/properties/type/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err6);
				errors++;
			} else {
				errors = _errs8;
				if (vErrors !== null) {
					if (_errs8) {
						vErrors.length = _errs8;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.id !== undefined) {
			let data3 = data.id;
			if (typeof data3 === "string") {
				if (!formats0(data3)) {
					const err7 = createError(
						instancePath + "/id",
						"#/allOf/0/properties/id/format",
						"format",
						{ format: "uri" },
						'must match format "' + "uri" + '"'
					);
					vErrors = pushError(vErrors, err7);
					errors++;
				}
			} else {
				const err8 = createError(
					instancePath + "/id",
					"#/allOf/0/properties/id/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err8);
				errors++;
			}
		}
		if (data.name !== undefined) {
			let data4 = data.name;
			const _errs24 = errors;
			let valid6 = false;
			const _errs25 = errors;
			if (typeof data4 !== "string") {
				const err9 = createError(
					instancePath + "/name",
					"#/allOf/0/properties/name/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err9);
				errors++;
			}
			var _valid2 = _errs25 === errors;
			valid6 = valid6 || _valid2;
			const _errs27 = errors;
			if (
				!keyword3(data4, {
					instancePath: instancePath + "/name",
					parentData: data,
					parentDataProperty: "name",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword3.errors : vErrors.concat(keyword3.errors);
				errors = vErrors.length;
			}
			var _valid2 = _errs27 === errors;
			valid6 = valid6 || _valid2;
			if (!valid6) {
				const err10 = createError(
					instancePath + "/name",
					"#/allOf/0/properties/name/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err10);
				errors++;
			} else {
				errors = _errs24;
				if (vErrors !== null) {
					if (_errs24) {
						vErrors.length = _errs24;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.nameMap !== undefined) {
			if (
				!keyword3(data.nameMap, {
					instancePath: instancePath + "/nameMap",
					parentData: data,
					parentDataProperty: "nameMap",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword3.errors : vErrors.concat(keyword3.errors);
				errors = vErrors.length;
			}
		}
		if (data.summary !== undefined) {
			let data6 = data.summary;
			const _errs32 = errors;
			let valid7 = false;
			const _errs33 = errors;
			if (typeof data6 !== "string") {
				const err11 = createError(
					instancePath + "/summary",
					"#/allOf/0/properties/summary/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err11);
				errors++;
			}
			var _valid3 = _errs33 === errors;
			valid7 = valid7 || _valid3;
			const _errs35 = errors;
			if (
				!keyword3(data6, {
					instancePath: instancePath + "/summary",
					parentData: data,
					parentDataProperty: "summary",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword3.errors : vErrors.concat(keyword3.errors);
				errors = vErrors.length;
			}
			var _valid3 = _errs35 === errors;
			valid7 = valid7 || _valid3;
			if (!valid7) {
				const err12 = createError(
					instancePath + "/summary",
					"#/allOf/0/properties/summary/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err12);
				errors++;
			} else {
				errors = _errs32;
				if (vErrors !== null) {
					if (_errs32) {
						vErrors.length = _errs32;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.summaryMap !== undefined) {
			if (
				!keyword3(data.summaryMap, {
					instancePath: instancePath + "/summaryMap",
					parentData: data,
					parentDataProperty: "summaryMap",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword3.errors : vErrors.concat(keyword3.errors);
				errors = vErrors.length;
			}
		}
		if (data.content !== undefined) {
			let data8 = data.content;
			const _errs40 = errors;
			let valid8 = false;
			const _errs41 = errors;
			if (typeof data8 !== "string") {
				const err13 = createError(
					instancePath + "/content",
					"#/allOf/0/properties/content/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err13);
				errors++;
			}
			var _valid4 = _errs41 === errors;
			valid8 = valid8 || _valid4;
			const _errs43 = errors;
			if (
				!keyword3(data8, {
					instancePath: instancePath + "/content",
					parentData: data,
					parentDataProperty: "content",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword3.errors : vErrors.concat(keyword3.errors);
				errors = vErrors.length;
			}
			var _valid4 = _errs43 === errors;
			valid8 = valid8 || _valid4;
			if (!valid8) {
				const err14 = createError(
					instancePath + "/content",
					"#/allOf/0/properties/content/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err14);
				errors++;
			} else {
				errors = _errs40;
				if (vErrors !== null) {
					if (_errs40) {
						vErrors.length = _errs40;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.contentMap !== undefined) {
			if (
				!keyword3(data.contentMap, {
					instancePath: instancePath + "/contentMap",
					parentData: data,
					parentDataProperty: "contentMap",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword3.errors : vErrors.concat(keyword3.errors);
				errors = vErrors.length;
			}
		}
		if (data.url !== undefined) {
			let data10 = data.url;
			const _errs48 = errors;
			let valid9 = false;
			const _errs49 = errors;
			if (typeof data10 !== "string") {
				const err15 = createError(
					instancePath + "/url",
					"#/allOf/0/properties/url/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err15);
				errors++;
			}
			var _valid5 = _errs49 === errors;
			valid9 = valid9 || _valid5;
			const _errs51 = errors;
			if (
				!keyword9(data10, {
					instancePath: instancePath + "/url",
					parentData: data,
					parentDataProperty: "url",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid5 = _errs51 === errors;
			valid9 = valid9 || _valid5;
			const _errs52 = errors;
			if (Array.isArray(data10)) {
				const len1 = data10.length;
				for (let i1 = 0; i1 < len1; i1++) {
					let data11 = data10[i1];
					const _errs55 = errors;
					let valid12 = false;
					const _errs56 = errors;
					if (typeof data11 !== "string") {
						const err16 = createError(
							instancePath + "/url/" + i1,
							"#/allOf/0/properties/url/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err16);
						errors++;
					}
					var _valid6 = _errs56 === errors;
					valid12 = valid12 || _valid6;
					const _errs58 = errors;
					if (
						!keyword9(data11, {
							instancePath: instancePath + "/url/" + i1,
							parentData: data10,
							parentDataProperty: i1,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid6 = _errs58 === errors;
					valid12 = valid12 || _valid6;
					if (!valid12) {
						const err17 = createError(
							instancePath + "/url/" + i1,
							"#/allOf/0/properties/url/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err17);
						errors++;
					} else {
						errors = _errs55;
						if (vErrors !== null) {
							if (_errs55) {
								vErrors.length = _errs55;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err18 = createError(
					instancePath + "/url",
					"#/allOf/0/properties/url/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err18);
				errors++;
			}
			var _valid5 = _errs52 === errors;
			valid9 = valid9 || _valid5;
			if (!valid9) {
				const err19 = createError(
					instancePath + "/url",
					"#/allOf/0/properties/url/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err19);
				errors++;
			} else {
				errors = _errs48;
				if (vErrors !== null) {
					if (_errs48) {
						vErrors.length = _errs48;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.image !== undefined) {
			let data12 = data.image;
			const _errs61 = errors;
			let valid13 = false;
			const _errs62 = errors;
			if (typeof data12 !== "string") {
				const err20 = createError(
					instancePath + "/image",
					"#/allOf/0/properties/image/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err20);
				errors++;
			}
			var _valid7 = _errs62 === errors;
			valid13 = valid13 || _valid7;
			const _errs64 = errors;
			if (
				!keyword9(data12, {
					instancePath: instancePath + "/image",
					parentData: data,
					parentDataProperty: "image",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid7 = _errs64 === errors;
			valid13 = valid13 || _valid7;
			const _errs65 = errors;
			if (Array.isArray(data12)) {
				const len2 = data12.length;
				for (let i2 = 0; i2 < len2; i2++) {
					let data13 = data12[i2];
					const _errs68 = errors;
					let valid16 = false;
					const _errs69 = errors;
					if (typeof data13 !== "string") {
						const err21 = createError(
							instancePath + "/image/" + i2,
							"#/allOf/0/properties/image/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err21);
						errors++;
					}
					var _valid8 = _errs69 === errors;
					valid16 = valid16 || _valid8;
					const _errs71 = errors;
					if (
						!keyword9(data13, {
							instancePath: instancePath + "/image/" + i2,
							parentData: data12,
							parentDataProperty: i2,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid8 = _errs71 === errors;
					valid16 = valid16 || _valid8;
					if (!valid16) {
						const err22 = createError(
							instancePath + "/image/" + i2,
							"#/allOf/0/properties/image/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err22);
						errors++;
					} else {
						errors = _errs68;
						if (vErrors !== null) {
							if (_errs68) {
								vErrors.length = _errs68;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err23 = createError(
					instancePath + "/image",
					"#/allOf/0/properties/image/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err23);
				errors++;
			}
			var _valid7 = _errs65 === errors;
			valid13 = valid13 || _valid7;
			if (!valid13) {
				const err24 = createError(
					instancePath + "/image",
					"#/allOf/0/properties/image/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err24);
				errors++;
			} else {
				errors = _errs61;
				if (vErrors !== null) {
					if (_errs61) {
						vErrors.length = _errs61;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.icon !== undefined) {
			let data14 = data.icon;
			const _errs74 = errors;
			let valid17 = false;
			const _errs75 = errors;
			if (typeof data14 !== "string") {
				const err25 = createError(
					instancePath + "/icon",
					"#/allOf/0/properties/icon/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err25);
				errors++;
			}
			var _valid9 = _errs75 === errors;
			valid17 = valid17 || _valid9;
			const _errs77 = errors;
			if (
				!keyword9(data14, {
					instancePath: instancePath + "/icon",
					parentData: data,
					parentDataProperty: "icon",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid9 = _errs77 === errors;
			valid17 = valid17 || _valid9;
			const _errs78 = errors;
			if (Array.isArray(data14)) {
				const len3 = data14.length;
				for (let i3 = 0; i3 < len3; i3++) {
					let data15 = data14[i3];
					const _errs81 = errors;
					let valid20 = false;
					const _errs82 = errors;
					if (typeof data15 !== "string") {
						const err26 = createError(
							instancePath + "/icon/" + i3,
							"#/allOf/0/properties/icon/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err26);
						errors++;
					}
					var _valid10 = _errs82 === errors;
					valid20 = valid20 || _valid10;
					const _errs84 = errors;
					if (
						!keyword9(data15, {
							instancePath: instancePath + "/icon/" + i3,
							parentData: data14,
							parentDataProperty: i3,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid10 = _errs84 === errors;
					valid20 = valid20 || _valid10;
					if (!valid20) {
						const err27 = createError(
							instancePath + "/icon/" + i3,
							"#/allOf/0/properties/icon/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err27);
						errors++;
					} else {
						errors = _errs81;
						if (vErrors !== null) {
							if (_errs81) {
								vErrors.length = _errs81;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err28 = createError(
					instancePath + "/icon",
					"#/allOf/0/properties/icon/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err28);
				errors++;
			}
			var _valid9 = _errs78 === errors;
			valid17 = valid17 || _valid9;
			if (!valid17) {
				const err29 = createError(
					instancePath + "/icon",
					"#/allOf/0/properties/icon/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err29);
				errors++;
			} else {
				errors = _errs74;
				if (vErrors !== null) {
					if (_errs74) {
						vErrors.length = _errs74;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.published !== undefined) {
			let data16 = data.published;
			if (typeof data16 === "string") {
				if (!formats2.validate(data16)) {
					const err30 = createError(
						instancePath + "/published",
						"#/allOf/0/properties/published/format",
						"format",
						{ format: "date-time" },
						'must match format "' + "date-time" + '"'
					);
					vErrors = pushError(vErrors, err30);
					errors++;
				}
			} else {
				const err31 = createError(
					instancePath + "/published",
					"#/allOf/0/properties/published/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err31);
				errors++;
			}
		}
		if (data.updated !== undefined) {
			let data17 = data.updated;
			if (typeof data17 === "string") {
				if (!formats2.validate(data17)) {
					const err32 = createError(
						instancePath + "/updated",
						"#/allOf/0/properties/updated/format",
						"format",
						{ format: "date-time" },
						'must match format "' + "date-time" + '"'
					);
					vErrors = pushError(vErrors, err32);
					errors++;
				}
			} else {
				const err33 = createError(
					instancePath + "/updated",
					"#/allOf/0/properties/updated/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err33);
				errors++;
			}
		}
		if (data.startTime !== undefined) {
			let data18 = data.startTime;
			if (typeof data18 === "string") {
				if (!formats2.validate(data18)) {
					const err34 = createError(
						instancePath + "/startTime",
						"#/allOf/0/properties/startTime/format",
						"format",
						{ format: "date-time" },
						'must match format "' + "date-time" + '"'
					);
					vErrors = pushError(vErrors, err34);
					errors++;
				}
			} else {
				const err35 = createError(
					instancePath + "/startTime",
					"#/allOf/0/properties/startTime/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err35);
				errors++;
			}
		}
		if (data.endTime !== undefined) {
			let data19 = data.endTime;
			if (typeof data19 === "string") {
				if (!formats2.validate(data19)) {
					const err36 = createError(
						instancePath + "/endTime",
						"#/allOf/0/properties/endTime/format",
						"format",
						{ format: "date-time" },
						'must match format "' + "date-time" + '"'
					);
					vErrors = pushError(vErrors, err36);
					errors++;
				}
			} else {
				const err37 = createError(
					instancePath + "/endTime",
					"#/allOf/0/properties/endTime/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err37);
				errors++;
			}
		}
		if (data.duration !== undefined) {
			let data20 = data.duration;
			if (typeof data20 === "string") {
				if (!formats10.test(data20)) {
					const err38 = createError(
						instancePath + "/duration",
						"#/allOf/0/properties/duration/format",
						"format",
						{ format: "duration" },
						'must match format "' + "duration" + '"'
					);
					vErrors = pushError(vErrors, err38);
					errors++;
				}
			} else {
				const err39 = createError(
					instancePath + "/duration",
					"#/allOf/0/properties/duration/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err39);
				errors++;
			}
		}
		if (data.generator !== undefined) {
			let data21 = data.generator;
			const _errs102 = errors;
			let valid21 = false;
			const _errs103 = errors;
			if (typeof data21 !== "string") {
				const err40 = createError(
					instancePath + "/generator",
					"#/allOf/0/properties/generator/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err40);
				errors++;
			}
			var _valid11 = _errs103 === errors;
			valid21 = valid21 || _valid11;
			const _errs105 = errors;
			if (
				!keyword9(data21, {
					instancePath: instancePath + "/generator",
					parentData: data,
					parentDataProperty: "generator",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid11 = _errs105 === errors;
			valid21 = valid21 || _valid11;
			const _errs106 = errors;
			if (Array.isArray(data21)) {
				const len4 = data21.length;
				for (let i4 = 0; i4 < len4; i4++) {
					let data22 = data21[i4];
					const _errs109 = errors;
					let valid24 = false;
					const _errs110 = errors;
					if (typeof data22 !== "string") {
						const err41 = createError(
							instancePath + "/generator/" + i4,
							"#/allOf/0/properties/generator/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err41);
						errors++;
					}
					var _valid12 = _errs110 === errors;
					valid24 = valid24 || _valid12;
					const _errs112 = errors;
					if (
						!keyword9(data22, {
							instancePath: instancePath + "/generator/" + i4,
							parentData: data21,
							parentDataProperty: i4,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid12 = _errs112 === errors;
					valid24 = valid24 || _valid12;
					if (!valid24) {
						const err42 = createError(
							instancePath + "/generator/" + i4,
							"#/allOf/0/properties/generator/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err42);
						errors++;
					} else {
						errors = _errs109;
						if (vErrors !== null) {
							if (_errs109) {
								vErrors.length = _errs109;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err43 = createError(
					instancePath + "/generator",
					"#/allOf/0/properties/generator/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err43);
				errors++;
			}
			var _valid11 = _errs106 === errors;
			valid21 = valid21 || _valid11;
			if (!valid21) {
				const err44 = createError(
					instancePath + "/generator",
					"#/allOf/0/properties/generator/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err44);
				errors++;
			} else {
				errors = _errs102;
				if (vErrors !== null) {
					if (_errs102) {
						vErrors.length = _errs102;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.attachment !== undefined) {
			let data23 = data.attachment;
			const _errs115 = errors;
			let valid25 = false;
			const _errs116 = errors;
			if (typeof data23 !== "string") {
				const err45 = createError(
					instancePath + "/attachment",
					"#/allOf/0/properties/attachment/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err45);
				errors++;
			}
			var _valid13 = _errs116 === errors;
			valid25 = valid25 || _valid13;
			const _errs118 = errors;
			if (
				!keyword9(data23, {
					instancePath: instancePath + "/attachment",
					parentData: data,
					parentDataProperty: "attachment",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid13 = _errs118 === errors;
			valid25 = valid25 || _valid13;
			const _errs119 = errors;
			if (Array.isArray(data23)) {
				const len5 = data23.length;
				for (let i5 = 0; i5 < len5; i5++) {
					let data24 = data23[i5];
					const _errs122 = errors;
					let valid28 = false;
					const _errs123 = errors;
					if (typeof data24 !== "string") {
						const err46 = createError(
							instancePath + "/attachment/" + i5,
							"#/allOf/0/properties/attachment/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err46);
						errors++;
					}
					var _valid14 = _errs123 === errors;
					valid28 = valid28 || _valid14;
					const _errs125 = errors;
					if (
						!keyword9(data24, {
							instancePath: instancePath + "/attachment/" + i5,
							parentData: data23,
							parentDataProperty: i5,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid14 = _errs125 === errors;
					valid28 = valid28 || _valid14;
					if (!valid28) {
						const err47 = createError(
							instancePath + "/attachment/" + i5,
							"#/allOf/0/properties/attachment/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err47);
						errors++;
					} else {
						errors = _errs122;
						if (vErrors !== null) {
							if (_errs122) {
								vErrors.length = _errs122;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err48 = createError(
					instancePath + "/attachment",
					"#/allOf/0/properties/attachment/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err48);
				errors++;
			}
			var _valid13 = _errs119 === errors;
			valid25 = valid25 || _valid13;
			if (!valid25) {
				const err49 = createError(
					instancePath + "/attachment",
					"#/allOf/0/properties/attachment/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err49);
				errors++;
			} else {
				errors = _errs115;
				if (vErrors !== null) {
					if (_errs115) {
						vErrors.length = _errs115;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.attributedTo !== undefined) {
			let data25 = data.attributedTo;
			const _errs128 = errors;
			let valid29 = false;
			const _errs129 = errors;
			if (typeof data25 !== "string") {
				const err50 = createError(
					instancePath + "/attributedTo",
					"#/allOf/0/properties/attributedTo/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err50);
				errors++;
			}
			var _valid15 = _errs129 === errors;
			valid29 = valid29 || _valid15;
			const _errs131 = errors;
			if (
				!keyword9(data25, {
					instancePath: instancePath + "/attributedTo",
					parentData: data,
					parentDataProperty: "attributedTo",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid15 = _errs131 === errors;
			valid29 = valid29 || _valid15;
			const _errs132 = errors;
			if (Array.isArray(data25)) {
				const len6 = data25.length;
				for (let i6 = 0; i6 < len6; i6++) {
					let data26 = data25[i6];
					const _errs135 = errors;
					let valid32 = false;
					const _errs136 = errors;
					if (typeof data26 !== "string") {
						const err51 = createError(
							instancePath + "/attributedTo/" + i6,
							"#/allOf/0/properties/attributedTo/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err51);
						errors++;
					}
					var _valid16 = _errs136 === errors;
					valid32 = valid32 || _valid16;
					const _errs138 = errors;
					if (
						!keyword9(data26, {
							instancePath: instancePath + "/attributedTo/" + i6,
							parentData: data25,
							parentDataProperty: i6,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid16 = _errs138 === errors;
					valid32 = valid32 || _valid16;
					if (!valid32) {
						const err52 = createError(
							instancePath + "/attributedTo/" + i6,
							"#/allOf/0/properties/attributedTo/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err52);
						errors++;
					} else {
						errors = _errs135;
						if (vErrors !== null) {
							if (_errs135) {
								vErrors.length = _errs135;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err53 = createError(
					instancePath + "/attributedTo",
					"#/allOf/0/properties/attributedTo/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err53);
				errors++;
			}
			var _valid15 = _errs132 === errors;
			valid29 = valid29 || _valid15;
			if (!valid29) {
				const err54 = createError(
					instancePath + "/attributedTo",
					"#/allOf/0/properties/attributedTo/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err54);
				errors++;
			} else {
				errors = _errs128;
				if (vErrors !== null) {
					if (_errs128) {
						vErrors.length = _errs128;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.audience !== undefined) {
			let data27 = data.audience;
			const _errs141 = errors;
			let valid33 = false;
			const _errs142 = errors;
			if (typeof data27 !== "string") {
				const err55 = createError(
					instancePath + "/audience",
					"#/allOf/0/properties/audience/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err55);
				errors++;
			}
			var _valid17 = _errs142 === errors;
			valid33 = valid33 || _valid17;
			const _errs144 = errors;
			if (
				!keyword9(data27, {
					instancePath: instancePath + "/audience",
					parentData: data,
					parentDataProperty: "audience",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid17 = _errs144 === errors;
			valid33 = valid33 || _valid17;
			const _errs145 = errors;
			if (Array.isArray(data27)) {
				const len7 = data27.length;
				for (let i7 = 0; i7 < len7; i7++) {
					let data28 = data27[i7];
					const _errs148 = errors;
					let valid36 = false;
					const _errs149 = errors;
					if (typeof data28 !== "string") {
						const err56 = createError(
							instancePath + "/audience/" + i7,
							"#/allOf/0/properties/audience/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err56);
						errors++;
					}
					var _valid18 = _errs149 === errors;
					valid36 = valid36 || _valid18;
					const _errs151 = errors;
					if (
						!keyword9(data28, {
							instancePath: instancePath + "/audience/" + i7,
							parentData: data27,
							parentDataProperty: i7,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid18 = _errs151 === errors;
					valid36 = valid36 || _valid18;
					if (!valid36) {
						const err57 = createError(
							instancePath + "/audience/" + i7,
							"#/allOf/0/properties/audience/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err57);
						errors++;
					} else {
						errors = _errs148;
						if (vErrors !== null) {
							if (_errs148) {
								vErrors.length = _errs148;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err58 = createError(
					instancePath + "/audience",
					"#/allOf/0/properties/audience/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err58);
				errors++;
			}
			var _valid17 = _errs145 === errors;
			valid33 = valid33 || _valid17;
			if (!valid33) {
				const err59 = createError(
					instancePath + "/audience",
					"#/allOf/0/properties/audience/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err59);
				errors++;
			} else {
				errors = _errs141;
				if (vErrors !== null) {
					if (_errs141) {
						vErrors.length = _errs141;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.context !== undefined) {
			let data29 = data.context;
			const _errs154 = errors;
			let valid37 = false;
			const _errs155 = errors;
			if (typeof data29 !== "string") {
				const err60 = createError(
					instancePath + "/context",
					"#/allOf/0/properties/context/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err60);
				errors++;
			}
			var _valid19 = _errs155 === errors;
			valid37 = valid37 || _valid19;
			const _errs157 = errors;
			if (
				!keyword9(data29, {
					instancePath: instancePath + "/context",
					parentData: data,
					parentDataProperty: "context",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid19 = _errs157 === errors;
			valid37 = valid37 || _valid19;
			const _errs158 = errors;
			if (Array.isArray(data29)) {
				const len8 = data29.length;
				for (let i8 = 0; i8 < len8; i8++) {
					let data30 = data29[i8];
					const _errs161 = errors;
					let valid40 = false;
					const _errs162 = errors;
					if (typeof data30 !== "string") {
						const err61 = createError(
							instancePath + "/context/" + i8,
							"#/allOf/0/properties/context/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err61);
						errors++;
					}
					var _valid20 = _errs162 === errors;
					valid40 = valid40 || _valid20;
					const _errs164 = errors;
					if (
						!keyword9(data30, {
							instancePath: instancePath + "/context/" + i8,
							parentData: data29,
							parentDataProperty: i8,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid20 = _errs164 === errors;
					valid40 = valid40 || _valid20;
					if (!valid40) {
						const err62 = createError(
							instancePath + "/context/" + i8,
							"#/allOf/0/properties/context/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err62);
						errors++;
					} else {
						errors = _errs161;
						if (vErrors !== null) {
							if (_errs161) {
								vErrors.length = _errs161;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err63 = createError(
					instancePath + "/context",
					"#/allOf/0/properties/context/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err63);
				errors++;
			}
			var _valid19 = _errs158 === errors;
			valid37 = valid37 || _valid19;
			if (!valid37) {
				const err64 = createError(
					instancePath + "/context",
					"#/allOf/0/properties/context/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err64);
				errors++;
			} else {
				errors = _errs154;
				if (vErrors !== null) {
					if (_errs154) {
						vErrors.length = _errs154;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.location !== undefined) {
			let data31 = data.location;
			const _errs167 = errors;
			let valid41 = false;
			const _errs168 = errors;
			if (typeof data31 !== "string") {
				const err65 = createError(
					instancePath + "/location",
					"#/allOf/0/properties/location/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err65);
				errors++;
			}
			var _valid21 = _errs168 === errors;
			valid41 = valid41 || _valid21;
			const _errs170 = errors;
			if (
				!keyword9(data31, {
					instancePath: instancePath + "/location",
					parentData: data,
					parentDataProperty: "location",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid21 = _errs170 === errors;
			valid41 = valid41 || _valid21;
			const _errs171 = errors;
			if (Array.isArray(data31)) {
				const len9 = data31.length;
				for (let i9 = 0; i9 < len9; i9++) {
					let data32 = data31[i9];
					const _errs174 = errors;
					let valid44 = false;
					const _errs175 = errors;
					if (typeof data32 !== "string") {
						const err66 = createError(
							instancePath + "/location/" + i9,
							"#/allOf/0/properties/location/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err66);
						errors++;
					}
					var _valid22 = _errs175 === errors;
					valid44 = valid44 || _valid22;
					const _errs177 = errors;
					if (
						!keyword9(data32, {
							instancePath: instancePath + "/location/" + i9,
							parentData: data31,
							parentDataProperty: i9,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid22 = _errs177 === errors;
					valid44 = valid44 || _valid22;
					if (!valid44) {
						const err67 = createError(
							instancePath + "/location/" + i9,
							"#/allOf/0/properties/location/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err67);
						errors++;
					} else {
						errors = _errs174;
						if (vErrors !== null) {
							if (_errs174) {
								vErrors.length = _errs174;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err68 = createError(
					instancePath + "/location",
					"#/allOf/0/properties/location/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err68);
				errors++;
			}
			var _valid21 = _errs171 === errors;
			valid41 = valid41 || _valid21;
			if (!valid41) {
				const err69 = createError(
					instancePath + "/location",
					"#/allOf/0/properties/location/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err69);
				errors++;
			} else {
				errors = _errs167;
				if (vErrors !== null) {
					if (_errs167) {
						vErrors.length = _errs167;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.tag !== undefined) {
			let data33 = data.tag;
			const _errs180 = errors;
			let valid45 = false;
			const _errs181 = errors;
			if (typeof data33 !== "string") {
				const err70 = createError(
					instancePath + "/tag",
					"#/allOf/0/properties/tag/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err70);
				errors++;
			}
			var _valid23 = _errs181 === errors;
			valid45 = valid45 || _valid23;
			const _errs183 = errors;
			if (
				!keyword9(data33, {
					instancePath: instancePath + "/tag",
					parentData: data,
					parentDataProperty: "tag",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid23 = _errs183 === errors;
			valid45 = valid45 || _valid23;
			const _errs184 = errors;
			if (Array.isArray(data33)) {
				const len10 = data33.length;
				for (let i10 = 0; i10 < len10; i10++) {
					let data34 = data33[i10];
					const _errs187 = errors;
					let valid48 = false;
					const _errs188 = errors;
					if (typeof data34 !== "string") {
						const err71 = createError(
							instancePath + "/tag/" + i10,
							"#/allOf/0/properties/tag/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err71);
						errors++;
					}
					var _valid24 = _errs188 === errors;
					valid48 = valid48 || _valid24;
					const _errs190 = errors;
					if (
						!keyword9(data34, {
							instancePath: instancePath + "/tag/" + i10,
							parentData: data33,
							parentDataProperty: i10,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid24 = _errs190 === errors;
					valid48 = valid48 || _valid24;
					if (!valid48) {
						const err72 = createError(
							instancePath + "/tag/" + i10,
							"#/allOf/0/properties/tag/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err72);
						errors++;
					} else {
						errors = _errs187;
						if (vErrors !== null) {
							if (_errs187) {
								vErrors.length = _errs187;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err73 = createError(
					instancePath + "/tag",
					"#/allOf/0/properties/tag/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err73);
				errors++;
			}
			var _valid23 = _errs184 === errors;
			valid45 = valid45 || _valid23;
			if (!valid45) {
				const err74 = createError(
					instancePath + "/tag",
					"#/allOf/0/properties/tag/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err74);
				errors++;
			} else {
				errors = _errs180;
				if (vErrors !== null) {
					if (_errs180) {
						vErrors.length = _errs180;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.inReplyTo !== undefined) {
			let data35 = data.inReplyTo;
			const _errs193 = errors;
			let valid49 = false;
			const _errs194 = errors;
			if (typeof data35 !== "string") {
				const err75 = createError(
					instancePath + "/inReplyTo",
					"#/allOf/0/properties/inReplyTo/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err75);
				errors++;
			}
			var _valid25 = _errs194 === errors;
			valid49 = valid49 || _valid25;
			const _errs196 = errors;
			if (
				!keyword9(data35, {
					instancePath: instancePath + "/inReplyTo",
					parentData: data,
					parentDataProperty: "inReplyTo",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid25 = _errs196 === errors;
			valid49 = valid49 || _valid25;
			const _errs197 = errors;
			if (Array.isArray(data35)) {
				const len11 = data35.length;
				for (let i11 = 0; i11 < len11; i11++) {
					let data36 = data35[i11];
					const _errs200 = errors;
					let valid52 = false;
					const _errs201 = errors;
					if (typeof data36 !== "string") {
						const err76 = createError(
							instancePath + "/inReplyTo/" + i11,
							"#/allOf/0/properties/inReplyTo/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err76);
						errors++;
					}
					var _valid26 = _errs201 === errors;
					valid52 = valid52 || _valid26;
					const _errs203 = errors;
					if (
						!keyword9(data36, {
							instancePath: instancePath + "/inReplyTo/" + i11,
							parentData: data35,
							parentDataProperty: i11,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid26 = _errs203 === errors;
					valid52 = valid52 || _valid26;
					if (!valid52) {
						const err77 = createError(
							instancePath + "/inReplyTo/" + i11,
							"#/allOf/0/properties/inReplyTo/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err77);
						errors++;
					} else {
						errors = _errs200;
						if (vErrors !== null) {
							if (_errs200) {
								vErrors.length = _errs200;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err78 = createError(
					instancePath + "/inReplyTo",
					"#/allOf/0/properties/inReplyTo/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err78);
				errors++;
			}
			var _valid25 = _errs197 === errors;
			valid49 = valid49 || _valid25;
			if (!valid49) {
				const err79 = createError(
					instancePath + "/inReplyTo",
					"#/allOf/0/properties/inReplyTo/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err79);
				errors++;
			} else {
				errors = _errs193;
				if (vErrors !== null) {
					if (_errs193) {
						vErrors.length = _errs193;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.replies !== undefined) {
			if (
				!keyword9(data.replies, {
					instancePath: instancePath + "/replies",
					parentData: data,
					parentDataProperty: "replies",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
		}
		if (data.preview !== undefined) {
			let data38 = data.preview;
			const _errs208 = errors;
			let valid53 = false;
			const _errs209 = errors;
			if (typeof data38 !== "string") {
				const err80 = createError(
					instancePath + "/preview",
					"#/allOf/0/properties/preview/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err80);
				errors++;
			}
			var _valid27 = _errs209 === errors;
			valid53 = valid53 || _valid27;
			const _errs211 = errors;
			if (
				!keyword9(data38, {
					instancePath: instancePath + "/preview",
					parentData: data,
					parentDataProperty: "preview",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid27 = _errs211 === errors;
			valid53 = valid53 || _valid27;
			const _errs212 = errors;
			if (Array.isArray(data38)) {
				const len12 = data38.length;
				for (let i12 = 0; i12 < len12; i12++) {
					let data39 = data38[i12];
					const _errs215 = errors;
					let valid56 = false;
					const _errs216 = errors;
					if (typeof data39 !== "string") {
						const err81 = createError(
							instancePath + "/preview/" + i12,
							"#/allOf/0/properties/preview/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err81);
						errors++;
					}
					var _valid28 = _errs216 === errors;
					valid56 = valid56 || _valid28;
					const _errs218 = errors;
					if (
						!keyword9(data39, {
							instancePath: instancePath + "/preview/" + i12,
							parentData: data38,
							parentDataProperty: i12,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid28 = _errs218 === errors;
					valid56 = valid56 || _valid28;
					if (!valid56) {
						const err82 = createError(
							instancePath + "/preview/" + i12,
							"#/allOf/0/properties/preview/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err82);
						errors++;
					} else {
						errors = _errs215;
						if (vErrors !== null) {
							if (_errs215) {
								vErrors.length = _errs215;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err83 = createError(
					instancePath + "/preview",
					"#/allOf/0/properties/preview/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err83);
				errors++;
			}
			var _valid27 = _errs212 === errors;
			valid53 = valid53 || _valid27;
			if (!valid53) {
				const err84 = createError(
					instancePath + "/preview",
					"#/allOf/0/properties/preview/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err84);
				errors++;
			} else {
				errors = _errs208;
				if (vErrors !== null) {
					if (_errs208) {
						vErrors.length = _errs208;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.to !== undefined) {
			let data40 = data.to;
			const _errs221 = errors;
			let valid57 = false;
			const _errs222 = errors;
			if (typeof data40 !== "string") {
				const err85 = createError(
					instancePath + "/to",
					"#/allOf/0/properties/to/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err85);
				errors++;
			}
			var _valid29 = _errs222 === errors;
			valid57 = valid57 || _valid29;
			const _errs224 = errors;
			if (
				!keyword9(data40, {
					instancePath: instancePath + "/to",
					parentData: data,
					parentDataProperty: "to",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid29 = _errs224 === errors;
			valid57 = valid57 || _valid29;
			const _errs225 = errors;
			if (Array.isArray(data40)) {
				const len13 = data40.length;
				for (let i13 = 0; i13 < len13; i13++) {
					let data41 = data40[i13];
					const _errs228 = errors;
					let valid60 = false;
					const _errs229 = errors;
					if (typeof data41 !== "string") {
						const err86 = createError(
							instancePath + "/to/" + i13,
							"#/allOf/0/properties/to/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err86);
						errors++;
					}
					var _valid30 = _errs229 === errors;
					valid60 = valid60 || _valid30;
					const _errs231 = errors;
					if (
						!keyword9(data41, {
							instancePath: instancePath + "/to/" + i13,
							parentData: data40,
							parentDataProperty: i13,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid30 = _errs231 === errors;
					valid60 = valid60 || _valid30;
					if (!valid60) {
						const err87 = createError(
							instancePath + "/to/" + i13,
							"#/allOf/0/properties/to/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err87);
						errors++;
					} else {
						errors = _errs228;
						if (vErrors !== null) {
							if (_errs228) {
								vErrors.length = _errs228;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err88 = createError(
					instancePath + "/to",
					"#/allOf/0/properties/to/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err88);
				errors++;
			}
			var _valid29 = _errs225 === errors;
			valid57 = valid57 || _valid29;
			if (!valid57) {
				const err89 = createError(
					instancePath + "/to",
					"#/allOf/0/properties/to/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err89);
				errors++;
			} else {
				errors = _errs221;
				if (vErrors !== null) {
					if (_errs221) {
						vErrors.length = _errs221;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.bto !== undefined) {
			let data42 = data.bto;
			const _errs234 = errors;
			let valid61 = false;
			const _errs235 = errors;
			if (typeof data42 !== "string") {
				const err90 = createError(
					instancePath + "/bto",
					"#/allOf/0/properties/bto/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err90);
				errors++;
			}
			var _valid31 = _errs235 === errors;
			valid61 = valid61 || _valid31;
			const _errs237 = errors;
			if (
				!keyword9(data42, {
					instancePath: instancePath + "/bto",
					parentData: data,
					parentDataProperty: "bto",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid31 = _errs237 === errors;
			valid61 = valid61 || _valid31;
			const _errs238 = errors;
			if (Array.isArray(data42)) {
				const len14 = data42.length;
				for (let i14 = 0; i14 < len14; i14++) {
					let data43 = data42[i14];
					const _errs241 = errors;
					let valid64 = false;
					const _errs242 = errors;
					if (typeof data43 !== "string") {
						const err91 = createError(
							instancePath + "/bto/" + i14,
							"#/allOf/0/properties/bto/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err91);
						errors++;
					}
					var _valid32 = _errs242 === errors;
					valid64 = valid64 || _valid32;
					const _errs244 = errors;
					if (
						!keyword9(data43, {
							instancePath: instancePath + "/bto/" + i14,
							parentData: data42,
							parentDataProperty: i14,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid32 = _errs244 === errors;
					valid64 = valid64 || _valid32;
					if (!valid64) {
						const err92 = createError(
							instancePath + "/bto/" + i14,
							"#/allOf/0/properties/bto/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err92);
						errors++;
					} else {
						errors = _errs241;
						if (vErrors !== null) {
							if (_errs241) {
								vErrors.length = _errs241;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err93 = createError(
					instancePath + "/bto",
					"#/allOf/0/properties/bto/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err93);
				errors++;
			}
			var _valid31 = _errs238 === errors;
			valid61 = valid61 || _valid31;
			if (!valid61) {
				const err94 = createError(
					instancePath + "/bto",
					"#/allOf/0/properties/bto/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err94);
				errors++;
			} else {
				errors = _errs234;
				if (vErrors !== null) {
					if (_errs234) {
						vErrors.length = _errs234;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.cc !== undefined) {
			let data44 = data.cc;
			const _errs247 = errors;
			let valid65 = false;
			const _errs248 = errors;
			if (typeof data44 !== "string") {
				const err95 = createError(
					instancePath + "/cc",
					"#/allOf/0/properties/cc/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err95);
				errors++;
			}
			var _valid33 = _errs248 === errors;
			valid65 = valid65 || _valid33;
			const _errs250 = errors;
			if (
				!keyword9(data44, {
					instancePath: instancePath + "/cc",
					parentData: data,
					parentDataProperty: "cc",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid33 = _errs250 === errors;
			valid65 = valid65 || _valid33;
			const _errs251 = errors;
			if (Array.isArray(data44)) {
				const len15 = data44.length;
				for (let i15 = 0; i15 < len15; i15++) {
					let data45 = data44[i15];
					const _errs254 = errors;
					let valid68 = false;
					const _errs255 = errors;
					if (typeof data45 !== "string") {
						const err96 = createError(
							instancePath + "/cc/" + i15,
							"#/allOf/0/properties/cc/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err96);
						errors++;
					}
					var _valid34 = _errs255 === errors;
					valid68 = valid68 || _valid34;
					const _errs257 = errors;
					if (
						!keyword9(data45, {
							instancePath: instancePath + "/cc/" + i15,
							parentData: data44,
							parentDataProperty: i15,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid34 = _errs257 === errors;
					valid68 = valid68 || _valid34;
					if (!valid68) {
						const err97 = createError(
							instancePath + "/cc/" + i15,
							"#/allOf/0/properties/cc/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err97);
						errors++;
					} else {
						errors = _errs254;
						if (vErrors !== null) {
							if (_errs254) {
								vErrors.length = _errs254;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err98 = createError(
					instancePath + "/cc",
					"#/allOf/0/properties/cc/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err98);
				errors++;
			}
			var _valid33 = _errs251 === errors;
			valid65 = valid65 || _valid33;
			if (!valid65) {
				const err99 = createError(
					instancePath + "/cc",
					"#/allOf/0/properties/cc/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err99);
				errors++;
			} else {
				errors = _errs247;
				if (vErrors !== null) {
					if (_errs247) {
						vErrors.length = _errs247;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.bcc !== undefined) {
			let data46 = data.bcc;
			const _errs260 = errors;
			let valid69 = false;
			const _errs261 = errors;
			if (typeof data46 !== "string") {
				const err100 = createError(
					instancePath + "/bcc",
					"#/allOf/0/properties/bcc/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err100);
				errors++;
			}
			var _valid35 = _errs261 === errors;
			valid69 = valid69 || _valid35;
			const _errs263 = errors;
			if (
				!keyword9(data46, {
					instancePath: instancePath + "/bcc",
					parentData: data,
					parentDataProperty: "bcc",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid35 = _errs263 === errors;
			valid69 = valid69 || _valid35;
			const _errs264 = errors;
			if (Array.isArray(data46)) {
				const len16 = data46.length;
				for (let i16 = 0; i16 < len16; i16++) {
					let data47 = data46[i16];
					const _errs267 = errors;
					let valid72 = false;
					const _errs268 = errors;
					if (typeof data47 !== "string") {
						const err101 = createError(
							instancePath + "/bcc/" + i16,
							"#/allOf/0/properties/bcc/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err101);
						errors++;
					}
					var _valid36 = _errs268 === errors;
					valid72 = valid72 || _valid36;
					const _errs270 = errors;
					if (
						!keyword9(data47, {
							instancePath: instancePath + "/bcc/" + i16,
							parentData: data46,
							parentDataProperty: i16,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid36 = _errs270 === errors;
					valid72 = valid72 || _valid36;
					if (!valid72) {
						const err102 = createError(
							instancePath + "/bcc/" + i16,
							"#/allOf/0/properties/bcc/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err102);
						errors++;
					} else {
						errors = _errs267;
						if (vErrors !== null) {
							if (_errs267) {
								vErrors.length = _errs267;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err103 = createError(
					instancePath + "/bcc",
					"#/allOf/0/properties/bcc/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err103);
				errors++;
			}
			var _valid35 = _errs264 === errors;
			valid69 = valid69 || _valid35;
			if (!valid69) {
				const err104 = createError(
					instancePath + "/bcc",
					"#/allOf/0/properties/bcc/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err104);
				errors++;
			} else {
				errors = _errs260;
				if (vErrors !== null) {
					if (_errs260) {
						vErrors.length = _errs260;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.mediaType !== undefined) {
			if (typeof data.mediaType !== "string") {
				const err105 = createError(
					instancePath + "/mediaType",
					"#/allOf/0/properties/mediaType/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err105);
				errors++;
			}
		}
		if (data.actor !== undefined) {
			let data49 = data.actor;
			const _errs276 = errors;
			let valid73 = false;
			const _errs277 = errors;
			if (typeof data49 !== "string") {
				const err106 = createError(
					instancePath + "/actor",
					"#/allOf/0/properties/actor/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err106);
				errors++;
			}
			var _valid37 = _errs277 === errors;
			valid73 = valid73 || _valid37;
			const _errs279 = errors;
			if (
				!keyword9(data49, {
					instancePath: instancePath + "/actor",
					parentData: data,
					parentDataProperty: "actor",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid37 = _errs279 === errors;
			valid73 = valid73 || _valid37;
			const _errs280 = errors;
			if (Array.isArray(data49)) {
				const len17 = data49.length;
				for (let i17 = 0; i17 < len17; i17++) {
					let data50 = data49[i17];
					const _errs283 = errors;
					let valid76 = false;
					const _errs284 = errors;
					if (typeof data50 !== "string") {
						const err107 = createError(
							instancePath + "/actor/" + i17,
							"#/allOf/0/properties/actor/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err107);
						errors++;
					}
					var _valid38 = _errs284 === errors;
					valid76 = valid76 || _valid38;
					const _errs286 = errors;
					if (
						!keyword9(data50, {
							instancePath: instancePath + "/actor/" + i17,
							parentData: data49,
							parentDataProperty: i17,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid38 = _errs286 === errors;
					valid76 = valid76 || _valid38;
					if (!valid76) {
						const err108 = createError(
							instancePath + "/actor/" + i17,
							"#/allOf/0/properties/actor/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err108);
						errors++;
					} else {
						errors = _errs283;
						if (vErrors !== null) {
							if (_errs283) {
								vErrors.length = _errs283;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err109 = createError(
					instancePath + "/actor",
					"#/allOf/0/properties/actor/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err109);
				errors++;
			}
			var _valid37 = _errs280 === errors;
			valid73 = valid73 || _valid37;
			if (!valid73) {
				const err110 = createError(
					instancePath + "/actor",
					"#/allOf/0/properties/actor/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err110);
				errors++;
			} else {
				errors = _errs276;
				if (vErrors !== null) {
					if (_errs276) {
						vErrors.length = _errs276;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.result !== undefined) {
			let data51 = data.result;
			const _errs289 = errors;
			let valid77 = false;
			const _errs290 = errors;
			if (typeof data51 !== "string") {
				const err111 = createError(
					instancePath + "/result",
					"#/allOf/0/properties/result/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err111);
				errors++;
			}
			var _valid39 = _errs290 === errors;
			valid77 = valid77 || _valid39;
			const _errs292 = errors;
			if (
				!keyword9(data51, {
					instancePath: instancePath + "/result",
					parentData: data,
					parentDataProperty: "result",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid39 = _errs292 === errors;
			valid77 = valid77 || _valid39;
			const _errs293 = errors;
			if (Array.isArray(data51)) {
				const len18 = data51.length;
				for (let i18 = 0; i18 < len18; i18++) {
					let data52 = data51[i18];
					const _errs296 = errors;
					let valid80 = false;
					const _errs297 = errors;
					if (typeof data52 !== "string") {
						const err112 = createError(
							instancePath + "/result/" + i18,
							"#/allOf/0/properties/result/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err112);
						errors++;
					}
					var _valid40 = _errs297 === errors;
					valid80 = valid80 || _valid40;
					const _errs299 = errors;
					if (
						!keyword9(data52, {
							instancePath: instancePath + "/result/" + i18,
							parentData: data51,
							parentDataProperty: i18,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid40 = _errs299 === errors;
					valid80 = valid80 || _valid40;
					if (!valid80) {
						const err113 = createError(
							instancePath + "/result/" + i18,
							"#/allOf/0/properties/result/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err113);
						errors++;
					} else {
						errors = _errs296;
						if (vErrors !== null) {
							if (_errs296) {
								vErrors.length = _errs296;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err114 = createError(
					instancePath + "/result",
					"#/allOf/0/properties/result/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err114);
				errors++;
			}
			var _valid39 = _errs293 === errors;
			valid77 = valid77 || _valid39;
			if (!valid77) {
				const err115 = createError(
					instancePath + "/result",
					"#/allOf/0/properties/result/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err115);
				errors++;
			} else {
				errors = _errs289;
				if (vErrors !== null) {
					if (_errs289) {
						vErrors.length = _errs289;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.origin !== undefined) {
			let data53 = data.origin;
			const _errs302 = errors;
			let valid81 = false;
			const _errs303 = errors;
			if (typeof data53 !== "string") {
				const err116 = createError(
					instancePath + "/origin",
					"#/allOf/0/properties/origin/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err116);
				errors++;
			}
			var _valid41 = _errs303 === errors;
			valid81 = valid81 || _valid41;
			const _errs305 = errors;
			if (
				!keyword9(data53, {
					instancePath: instancePath + "/origin",
					parentData: data,
					parentDataProperty: "origin",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid41 = _errs305 === errors;
			valid81 = valid81 || _valid41;
			const _errs306 = errors;
			if (Array.isArray(data53)) {
				const len19 = data53.length;
				for (let i19 = 0; i19 < len19; i19++) {
					let data54 = data53[i19];
					const _errs309 = errors;
					let valid84 = false;
					const _errs310 = errors;
					if (typeof data54 !== "string") {
						const err117 = createError(
							instancePath + "/origin/" + i19,
							"#/allOf/0/properties/origin/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err117);
						errors++;
					}
					var _valid42 = _errs310 === errors;
					valid84 = valid84 || _valid42;
					const _errs312 = errors;
					if (
						!keyword9(data54, {
							instancePath: instancePath + "/origin/" + i19,
							parentData: data53,
							parentDataProperty: i19,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid42 = _errs312 === errors;
					valid84 = valid84 || _valid42;
					if (!valid84) {
						const err118 = createError(
							instancePath + "/origin/" + i19,
							"#/allOf/0/properties/origin/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err118);
						errors++;
					} else {
						errors = _errs309;
						if (vErrors !== null) {
							if (_errs309) {
								vErrors.length = _errs309;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err119 = createError(
					instancePath + "/origin",
					"#/allOf/0/properties/origin/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err119);
				errors++;
			}
			var _valid41 = _errs306 === errors;
			valid81 = valid81 || _valid41;
			if (!valid81) {
				const err120 = createError(
					instancePath + "/origin",
					"#/allOf/0/properties/origin/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err120);
				errors++;
			} else {
				errors = _errs302;
				if (vErrors !== null) {
					if (_errs302) {
						vErrors.length = _errs302;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.instrument !== undefined) {
			let data55 = data.instrument;
			const _errs315 = errors;
			let valid85 = false;
			const _errs316 = errors;
			if (typeof data55 !== "string") {
				const err121 = createError(
					instancePath + "/instrument",
					"#/allOf/0/properties/instrument/anyOf/0/type",
					"type",
					{ type: "string" },
					0
				);
				vErrors = pushError(vErrors, err121);
				errors++;
			}
			var _valid43 = _errs316 === errors;
			valid85 = valid85 || _valid43;
			const _errs318 = errors;
			if (
				!keyword9(data55, {
					instancePath: instancePath + "/instrument",
					parentData: data,
					parentDataProperty: "instrument",
					rootData,
					dynamicAnchors
				})
			) {
				vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
				errors = vErrors.length;
			}
			var _valid43 = _errs318 === errors;
			valid85 = valid85 || _valid43;
			const _errs319 = errors;
			if (Array.isArray(data55)) {
				const len20 = data55.length;
				for (let i20 = 0; i20 < len20; i20++) {
					let data56 = data55[i20];
					const _errs322 = errors;
					let valid88 = false;
					const _errs323 = errors;
					if (typeof data56 !== "string") {
						const err122 = createError(
							instancePath + "/instrument/" + i20,
							"#/allOf/0/properties/instrument/anyOf/2/items/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err122);
						errors++;
					}
					var _valid44 = _errs323 === errors;
					valid88 = valid88 || _valid44;
					const _errs325 = errors;
					if (
						!keyword9(data56, {
							instancePath: instancePath + "/instrument/" + i20,
							parentData: data55,
							parentDataProperty: i20,
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword9.errors : vErrors.concat(keyword9.errors);
						errors = vErrors.length;
					}
					var _valid44 = _errs325 === errors;
					valid88 = valid88 || _valid44;
					if (!valid88) {
						const err123 = createError(
							instancePath + "/instrument/" + i20,
							"#/allOf/0/properties/instrument/anyOf/2/items/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err123);
						errors++;
					} else {
						errors = _errs322;
						if (vErrors !== null) {
							if (_errs322) {
								vErrors.length = _errs322;
							} else {
								vErrors = null;
							}
						}
					}
				}
			} else {
				const err124 = createError(
					instancePath + "/instrument",
					"#/allOf/0/properties/instrument/anyOf/2/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err124);
				errors++;
			}
			var _valid43 = _errs319 === errors;
			valid85 = valid85 || _valid43;
			if (!valid85) {
				const err125 = createError(
					instancePath + "/instrument",
					"#/allOf/0/properties/instrument/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err125);
				errors++;
			} else {
				errors = _errs315;
				if (vErrors !== null) {
					if (_errs315) {
						vErrors.length = _errs315;
					} else {
						vErrors = null;
					}
				}
			}
		}
	} else {
		const err126 = createError(instancePath, "#/allOf/0/type", "type", { type: "object" }, 3);
		vErrors = pushError(vErrors, err126);
		errors++;
	}
	if (data && typeof data == "object" && !Array.isArray(data)) {
		if (data.object === undefined) {
			const err127 = createError(
				instancePath,
				"#/required",
				"required",
				{ missingProperty: "object" },
				"must have required property '" + "object" + "'"
			);
			vErrors = pushError(vErrors, err127);
			errors++;
		}
		if (data.object !== undefined) {
			let data57 = data.object;
			const _errs327 = errors;
			let valid90 = false;
			const _errs328 = errors;
			if (data57 && typeof data57 == "object" && !Array.isArray(data57)) {
				if (data57.type === undefined) {
					const err128 = createError(
						instancePath + "/object",
						"#/properties/object/anyOf/0/required",
						"required",
						{ missingProperty: "type" },
						"must have required property '" + "type" + "'"
					);
					vErrors = pushError(vErrors, err128);
					errors++;
				}
				if (data57["@context"] === undefined) {
					const err129 = createError(
						instancePath + "/object",
						"#/properties/object/anyOf/0/required",
						"required",
						{ missingProperty: "@context" },
						"must have required property '" + "@context" + "'"
					);
					vErrors = pushError(vErrors, err129);
					errors++;
				}
				if (data57.type !== undefined) {
					let data58 = data57.type;
					const _errs332 = errors;
					let valid92 = false;
					const _errs333 = errors;
					if (typeof data58 !== "string") {
						const err130 = createError(
							instancePath + "/object/type",
							"#/properties/object/anyOf/0/properties/type/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err130);
						errors++;
					}
					var _valid46 = _errs333 === errors;
					valid92 = valid92 || _valid46;
					const _errs335 = errors;
					if (Array.isArray(data58)) {
						const len21 = data58.length;
						for (let i21 = 0; i21 < len21; i21++) {
							if (typeof data58[i21] !== "string") {
								const err131 = createError(
									instancePath + "/object/type/" + i21,
									"#/properties/object/anyOf/0/properties/type/anyOf/1/items/type",
									"type",
									{ type: "string" },
									0
								);
								vErrors = pushError(vErrors, err131);
								errors++;
							}
						}
					} else {
						const err132 = createError(
							instancePath + "/object/type",
							"#/properties/object/anyOf/0/properties/type/anyOf/1/type",
							"type",
							{ type: "array" },
							2
						);
						vErrors = pushError(vErrors, err132);
						errors++;
					}
					var _valid46 = _errs335 === errors;
					valid92 = valid92 || _valid46;
					if (!valid92) {
						const err133 = createError(
							instancePath + "/object/type",
							"#/properties/object/anyOf/0/properties/type/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err133);
						errors++;
					} else {
						errors = _errs332;
						if (vErrors !== null) {
							if (_errs332) {
								vErrors.length = _errs332;
							} else {
								vErrors = null;
							}
						}
					}
				}
				if (data57["@context"] !== undefined) {
					if (
						!keyword50(data57["@context"], {
							instancePath: instancePath + "/object/@context",
							parentData: data57,
							parentDataProperty: "@context",
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword50.errors : vErrors.concat(keyword50.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err134 = createError(
					instancePath + "/object",
					"#/properties/object/anyOf/0/type",
					"type",
					{ type: "object" },
					3
				);
				vErrors = pushError(vErrors, err134);
				errors++;
			}
			var _valid45 = _errs328 === errors;
			valid90 = valid90 || _valid45;
			if (_valid45) {
				var props44 = {};
				props44.type = true;
				props44["@context"] = true;
			}
			const _errs340 = errors;
			if (Array.isArray(data57)) {
				const len22 = data57.length;
				for (let i22 = 0; i22 < len22; i22++) {
					let data61 = data57[i22];
					if (data61 && typeof data61 == "object" && !Array.isArray(data61)) {
						if (data61.type === undefined) {
							const err135 = createError(
								instancePath + "/object/" + i22,
								"#/properties/object/anyOf/1/items/required",
								"required",
								{ missingProperty: "type" },
								"must have required property '" + "type" + "'"
							);
							vErrors = pushError(vErrors, err135);
							errors++;
						}
						if (data61["@context"] === undefined) {
							const err136 = createError(
								instancePath + "/object/" + i22,
								"#/properties/object/anyOf/1/items/required",
								"required",
								{ missingProperty: "@context" },
								"must have required property '" + "@context" + "'"
							);
							vErrors = pushError(vErrors, err136);
							errors++;
						}
						if (data61.type !== undefined) {
							let data62 = data61.type;
							const _errs346 = errors;
							let valid98 = false;
							const _errs347 = errors;
							if (typeof data62 !== "string") {
								const err137 = createError(
									instancePath + "/object/" + i22 + "/type",
									"#/properties/object/anyOf/1/items/properties/type/anyOf/0/type",
									"type",
									{ type: "string" },
									0
								);
								vErrors = pushError(vErrors, err137);
								errors++;
							}
							var _valid47 = _errs347 === errors;
							valid98 = valid98 || _valid47;
							const _errs349 = errors;
							if (Array.isArray(data62)) {
								const len23 = data62.length;
								for (let i23 = 0; i23 < len23; i23++) {
									if (typeof data62[i23] !== "string") {
										const err138 = createError(
											instancePath + "/object/" + i22 + "/type/" + i23,
											"#/properties/object/anyOf/1/items/properties/type/anyOf/1/items/type",
											"type",
											{ type: "string" },
											0
										);
										vErrors = pushError(vErrors, err138);
										errors++;
									}
								}
							} else {
								const err139 = createError(
									instancePath + "/object/" + i22 + "/type",
									"#/properties/object/anyOf/1/items/properties/type/anyOf/1/type",
									"type",
									{ type: "array" },
									2
								);
								vErrors = pushError(vErrors, err139);
								errors++;
							}
							var _valid47 = _errs349 === errors;
							valid98 = valid98 || _valid47;
							if (!valid98) {
								const err140 = createError(
									instancePath + "/object/" + i22 + "/type",
									"#/properties/object/anyOf/1/items/properties/type/anyOf",
									"anyOf",
									{},
									1
								);
								vErrors = pushError(vErrors, err140);
								errors++;
							} else {
								errors = _errs346;
								if (vErrors !== null) {
									if (_errs346) {
										vErrors.length = _errs346;
									} else {
										vErrors = null;
									}
								}
							}
						}
						if (data61["@context"] !== undefined) {
							if (
								!keyword50(data61["@context"], {
									instancePath: instancePath + "/object/" + i22 + "/@context",
									parentData: data61,
									parentDataProperty: "@context",
									rootData,
									dynamicAnchors
								})
							) {
								vErrors = vErrors === null ? keyword50.errors : vErrors.concat(keyword50.errors);
								errors = vErrors.length;
							}
						}
					} else {
						const err141 = createError(
							instancePath + "/object/" + i22,
							"#/properties/object/anyOf/1/items/type",
							"type",
							{ type: "object" },
							3
						);
						vErrors = pushError(vErrors, err141);
						errors++;
					}
				}
			} else {
				const err142 = createError(
					instancePath + "/object",
					"#/properties/object/anyOf/1/type",
					"type",
					{ type: "array" },
					2
				);
				vErrors = pushError(vErrors, err142);
				errors++;
			}
			var _valid45 = _errs340 === errors;
			valid90 = valid90 || _valid45;
			if (!valid90) {
				const err143 = createError(
					instancePath + "/object",
					"#/properties/object/anyOf",
					"anyOf",
					{},
					1
				);
				vErrors = pushError(vErrors, err143);
				errors++;
			} else {
				errors = _errs327;
				if (vErrors !== null) {
					if (_errs327) {
						vErrors.length = _errs327;
					} else {
						vErrors = null;
					}
				}
			}
		}
		if (data.target !== undefined) {
			let data65 = data.target;
			if (data65 && typeof data65 == "object" && !Array.isArray(data65)) {
				if (data65.type === undefined) {
					const err144 = createError(
						instancePath + "/target",
						"#/properties/target/required",
						"required",
						{ missingProperty: "type" },
						"must have required property '" + "type" + "'"
					);
					vErrors = pushError(vErrors, err144);
					errors++;
				}
				if (data65["@context"] === undefined) {
					const err145 = createError(
						instancePath + "/target",
						"#/properties/target/required",
						"required",
						{ missingProperty: "@context" },
						"must have required property '" + "@context" + "'"
					);
					vErrors = pushError(vErrors, err145);
					errors++;
				}
				if (data65.type !== undefined) {
					let data66 = data65.type;
					const _errs358 = errors;
					let valid102 = false;
					const _errs359 = errors;
					if (typeof data66 !== "string") {
						const err146 = createError(
							instancePath + "/target/type",
							"#/properties/target/properties/type/anyOf/0/type",
							"type",
							{ type: "string" },
							0
						);
						vErrors = pushError(vErrors, err146);
						errors++;
					}
					var _valid48 = _errs359 === errors;
					valid102 = valid102 || _valid48;
					const _errs361 = errors;
					if (Array.isArray(data66)) {
						const len24 = data66.length;
						for (let i24 = 0; i24 < len24; i24++) {
							if (typeof data66[i24] !== "string") {
								const err147 = createError(
									instancePath + "/target/type/" + i24,
									"#/properties/target/properties/type/anyOf/1/items/type",
									"type",
									{ type: "string" },
									0
								);
								vErrors = pushError(vErrors, err147);
								errors++;
							}
						}
					} else {
						const err148 = createError(
							instancePath + "/target/type",
							"#/properties/target/properties/type/anyOf/1/type",
							"type",
							{ type: "array" },
							2
						);
						vErrors = pushError(vErrors, err148);
						errors++;
					}
					var _valid48 = _errs361 === errors;
					valid102 = valid102 || _valid48;
					if (!valid102) {
						const err149 = createError(
							instancePath + "/target/type",
							"#/properties/target/properties/type/anyOf",
							"anyOf",
							{},
							1
						);
						vErrors = pushError(vErrors, err149);
						errors++;
					} else {
						errors = _errs358;
						if (vErrors !== null) {
							if (_errs358) {
								vErrors.length = _errs358;
							} else {
								vErrors = null;
							}
						}
					}
				}
				if (data65["@context"] !== undefined) {
					if (
						!keyword50(data65["@context"], {
							instancePath: instancePath + "/target/@context",
							parentData: data65,
							parentDataProperty: "@context",
							rootData,
							dynamicAnchors
						})
					) {
						vErrors = vErrors === null ? keyword50.errors : vErrors.concat(keyword50.errors);
						errors = vErrors.length;
					}
				}
			} else {
				const err150 = createError(
					instancePath + "/target",
					"#/properties/target/type",
					"type",
					{ type: "object" },
					3
				);
				vErrors = pushError(vErrors, err150);
				errors++;
			}
		}
	} else {
		const err151 = createError(instancePath, "#/type", "type", { type: "object" }, 3);
		vErrors = pushError(vErrors, err151);
		errors++;
	}
	validate52.errors = vErrors;
	return errors === 0;
}
validate52.evaluated = {
	props: {
		object: true,
		target: true,
		"@context": true,
		type: true,
		id: true,
		name: true,
		nameMap: true,
		summary: true,
		summaryMap: true,
		content: true,
		contentMap: true,
		url: true,
		image: true,
		icon: true,
		published: true,
		updated: true,
		startTime: true,
		endTime: true,
		duration: true,
		generator: true,
		attachment: true,
		attributedTo: true,
		audience: true,
		context: true,
		location: true,
		tag: true,
		inReplyTo: true,
		replies: true,
		preview: true,
		to: true,
		bto: true,
		cc: true,
		bcc: true,
		mediaType: true,
		actor: true,
		result: true,
		origin: true,
		instrument: true
	},
	dynamicProps: false,
	dynamicItems: false
};
